### PR TITLE
Fix: #7 - Add rate-limiting using DRF

### PR DESCRIPTION
**Pull request by JathinShyam**
This fixes the Rate-limiting and throttling issues. added scopes for different types. This provides the ability to customize the rate per user.
Tried my best. Iam a beginner to open source. Let me know the changes are good or not.  I will work on it. Thanks!

### CODE REVIEW

**Review by fjsj — CHANGES_REQUESTED** [review]
hi @JathinShyam, thanks for the contribution! We're looking for ways to implement rate limiting without adding a new (large) dependency like Django REST framework. Since the app already uses Django Ninja, it would be better to have a solution with it. Also, you've implemented the rate limiting on the example project, but not in the lib Django app. Probably we need something [like this](https://youtu.be/yQqig-c2dd4?t=1059), which requires django-ninja-extra, an extra dep, but at least it still is in Django Ninja domain, not DRF.

**Comment by JathinShyam** [comment]
Sorry for the confusion. I didn't know your intention behind this DRF. I saw the Youtube video and it seems very easy. Is that enough for this? Let me know what other changes need to be done.

**Comment by fjsj** [comment]
@JathinShyam probably enough, but it's also necessary to:
- update dependencies
- write tests
- update docs

Feel free to give it a try in this PR or another one. Thanks.

**Comment by JathinShyam** [comment]
Thanks for the confirmation. I am new to this django-ninja. Before this one, I didn't know this exists. Thanks to you, I got opportunity to learn. I will take some time and try to contribute.

**Comment by fjsj** [comment]
Closing due to lack of activity. Feel free to open a new PR after addressing issues.

**Pull request closed without merging**
